# Site settings
title: AdijayaInc Notes
author:
  name: Adijaya
  email: adijaya@gmail.com
description: "The worlds of Adijaya."
github_username: adijayainc

# Email and twitter are optional:
email: trias.adijaya@gmail.com
twitter_username: adijayainc


# Build settings
remote_theme: jekyll/minima
# theme: minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  
header_pages:
  - about.md
  - portfolio.md

# Set this to true to get LaTeX math equation support
use_math: null

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: null

# Everything below here can be ignored, unless you want to change the theme entirely
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
