# Site settings
title: AdijayaInc Notes
author:
  name: Adijaya
  email: adijaya@gmail.com
description: "The worlds of Adijaya."

# Build settings
remote_theme: jekyll/minima

# theme: minima
header_pages:
  - about.md
  - portfolio.md

  show_excerpts: true
