title: AdijayaInc Project 
author:
  name: Trias Adijaya
  email: trias.adijaya@gmail.com
  
# logo: /assets/img/digitalneo.png
description: "Your partner in digital world"
show_downloads: true
# theme: jekyll-theme-minimal
theme: jekyll-theme-minima
